version: '3'
services:
  db:
    container_name: postgres
    restart: always
    image: postgres:12.11-alpine
    env_file:
      - db.env
    # todo: Careful about the target folder. A wrong configuration
    # leads to data loss after "docker compose down".
    # The current setup seems to work fine.
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./scripts:/tmp/scripts
  backend:
    image: nikitadanilenko/foodie:latest
    ports:
      - "9001:9000"
    env_file:
      - deployment.env
    depends_on:
      - db
volumes:
  postgres-data:
  scripts:

