version: '3'
services:
  backend:
    build: target/docker/stage
    ports:
      - "9001:9001"
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: postgres
    restart: always
    image: postgres:12.11-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"