name: Auto-merge Pull Requests

on:
  workflow_call:
    secrets:
      github-token:
        description: 'GitHub token with permissions to approve and merge pull requests'
        required: true

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    env:
      MERGE_TOKEN: ${{ secrets.github-token }}
    steps:
      - name: Log in to GitHub CLI
        run: echo ${{ env.MERGE_TOKEN }} | gh auth login --with-token
      - name: Approve Pull Request
        run: gh pr review --approve ${{ github.event.pull_request.html_url }}
      - name: Merge Pull Request
        run: gh pr merge --auto --squash ${{ github.event.pull_request.html_url }}
