name: Auto-merge Scala Steward Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  debug_length:
    runs-on: ubuntu-latest
    steps:
      - name: Debug length
        run: |
          echo {#{{ secrets.AUTO_MERGE_TOKEN }}} 

  call_auto_merge:
    if: github.event.pull_request.user.login == 'scala-steward'
    uses: ./.github/workflows/auto-merge-pull-requests.yml
    secrets:
      merge-token: ${{ secrets.AUTO_MERGE_TOKEN }}
