name: Auto-merge Pull Requests

on:
  workflow_call:
    secrets:
      merge-token:
        description: 'GitHub token with permissions to approve and merge pull requests'
        required: true

env:
  GH_TOKEN: ${{ secrets.merge-token }}

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Debug length
        run: |
          echo "Length of GH_TOKEN: ${#GH_TOKEN}"
      - name: Log in to GitHub CLI
        run: echo ${{ env.GH_TOKEN }} | gh auth login --with-token
      - name: Approve Pull Request
        run: gh pr review --approve ${{ github.event.pull_request.html_url }}
      - name: Merge Pull Request
        run: gh pr merge --auto --squash ${{ github.event.pull_request.html_url }}
