name: Auto-merge Pull Requests

on:
  workflow_call:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub CLI
        run: echo ${{ secrets.AUTO_MERGE_TOKEN }} | gh auth login --with-token
      - name: Approve Pull Request
        run: gh pr review --approve ${{ github.event.pull_request.html_url }}
      - name: Merge Pull Request
        run: gh pr merge --auto --squash ${{ github.event.pull_request.html_url }}
