name: Auto-merge Dependabot Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:

  # Dependabot mostly concerns GitHub Actions, so we only auto-merge non-major updates.
  fetch_metadata:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    outputs:
      update-type: ${{ steps.dependabot-metadata.outputs.update-type }}
    steps:
      - name: Fetch Dependabot Metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # v2.4.0

  call_auto_merge:
    needs:
      - fetch_metadata
    if: needs.fetch_metadata.outputs.update-type != 'version-update:semver-major'
    uses: ./.github/workflows/auto-merge-pull-requests.yml
    secrets:
      merge-token: ${{ secrets.GITHUB_TOKEN }}
