name: Auto-merge Scala Steward Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  call_auto_merge:
    if: github.event.pull_request.user.login == 'scala-steward'
    uses: ./.github/workflows/auto-merge-pull-requests.yml
    secrets: inherit
