name: Build and publish front end

on:
  push:
    branches:
      - "main"
    paths:
      - frontend/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '20.x'
      - name: Install create-elm-app
        run: npm install create-elm-app -g
      - name: Build Elm app
#       The secret handling is questionable,
#       because the variables are readable from the result.
        run: |
          cd frontend
          rm .env
          export ELM_APP_BACKEND_URL=${{ secrets.ELM_APP_BACKEND_URL }}
          export ELM_APP_MAIN_PAGE_URL=${{ secrets.ELM_APP_MAIN_PAGE_URL }}
          elm-app build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      - name: Login to DockerHub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Set metadata
        id: metadata
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: nikitadanilenko/foodie-frontend
          tags: |
            type=sha
            type=raw,value=latest
      - name: Build and push Docker image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: frontend
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
