name: Build and publish front end

on:
  workflow_call:
    inputs:
      version-tag:
        type: string
        required: true

permissions:
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish
        uses: ./.github/actions/build-and-publish
        with:
          version-tag: ${{ inputs.version-tag }}
          image-name: nikitadanilenko/foodie-frontend
          context: frontend
          docker-hub-username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker-hub-token: ${{ secrets.DOCKER_HUB_TOKEN }}
