name: Build and publish back end

on:
  workflow_call:
    inputs:
      version-tag:
        type: string
        required: true

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up JDK 17
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
      # Technically, we could use 'sbt "Docker / publish"',
      # but one would need to handle the credentials elsewhere.
      - name: Prepare Docker image
        run: sbt "Docker / stage"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
      - name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Set metadata
        id: metadata
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: nikitadanilenko/foodie
          tags: |
            type=sha
            type=raw,value=latest
            type=semver,pattern={{version}},value=${{ inputs.version-tag }}
      - name: Build and push Docker image
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          context: target/docker/stage
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
