name: Build and publish back end

on:
  workflow_call:
    inputs:
      version-tag:
        type: string
        required: true

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Set up JDK 17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
      # Technically, we could use 'sbt "Docker / publish"',
      # but one would need to handle the credentials elsewhere.
      - name: Prepare Docker image
        run: sbt "Docker / stage"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - name: Login to DockerHub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Set metadata
        id: metadata
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: nikitadanilenko/foodie
          tags: |
            type=sha
            type=raw,value=latest
            type=semver,pattern={{version}},value=${{ inputs.version-tag }}
      - name: Build and push Docker image
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          context: target/docker/stage
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
