name: Build and publish back end

on:
  workflow_call:
    inputs:
      version-tag:
        type: string
        required: true

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up JDK 17
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Set up SBT
        uses: sbt/setup-sbt@96cf3f09dc501acdad7807fffe97dba9fa0709be # v1.1.5
      # Technically, we could use 'sbt "Docker / publish"',
      # but one would need to handle the credentials elsewhere.
      - name: Prepare Docker image
        run: sbt "Docker / stage"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0
      - name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Set metadata
        id: metadata
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: nikitadanilenko/foodie
          tags: |
            type=sha
            type=raw,value=latest
            type=semver,pattern={{version}},value=${{ inputs.version-tag }}
      - name: Build and push Docker image
        uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d # v6.12.0
        with:
          context: target/docker/stage
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
