name: Build and publish front end

on:
  workflow_call:
    inputs:
      version-tag:
        type: string
        required: true

permissions:
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          # Outdated. Updating to 17+ introduces a breaking change with create-elm-app.
          node-version: '16.x'
      - name: Install create-elm-app
        run: npm install create-elm-app -g
      - name: Build Elm app
#       The secret handling is questionable,
#       because the variables are readable from the result.
        run: |
          cd frontend
          rm .env
          export ELM_APP_BACKEND_URL=${{ secrets.ELM_APP_BACKEND_URL }}
          export ELM_APP_MAIN_PAGE_URL=${{ secrets.ELM_APP_MAIN_PAGE_URL }}
          elm-app build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
      - name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Set metadata
        id: metadata
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: nikitadanilenko/foodie-frontend
          tags: |
            type=sha
            type=raw,value=latest
            type=semver,pattern={{version}},value=${{ inputs.version-tag }}
      - name: Build and push Docker image
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          context: frontend
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
