name: Build and publish components

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  determine_changes_and_version:
    runs-on: ubuntu-latest
    outputs:
      version-tag: ${{ steps.semantic-version.outputs.version_tag }}
      back-end-paths-changed: ${{ steps.back-end.outputs.back-end-src }}
      front-end-paths-changed: ${{ steps.front-end.outputs.front-end-src }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        # Depth setting is necessary for the semantic-version action.
        with:
          fetch-depth: 0
      - name: Determine version
        id: semantic-version
        uses: paulhatch/semantic-version@a8f8f59fd7f0625188492e945240f12d7ad2dca3 # v5.4.0
      - uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd # v3.0.0
        id: back-end
        with:
          filters: |
            back-end-src:
              - 'app/**'
              - 'test/**' 
              - 'conf/**' 
              - 'scripts/**'
              - 'build.sbt'
              - 'project/**'
              - '.scalafmt.conf'
      - uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd # v3.0.0
        id: front-end
        with:
          filters: |
            front-end-src:
              - 'frontend/**'

  build_and_publish_back_end:
    needs: determine_changes_and_version
    uses: ./.github/workflows/build-and-publish-back-end.yml
    # The output is a string, hence the string comparison.
    if: ${{ needs.determine_changes_and_version.outputs.back-end-paths-changed == 'true' }}
    with:
      version-tag: ${{ needs.determine_changes_and_version.outputs.version-tag }}
    secrets: inherit

  build_and_publish_front_end:
    needs: determine_changes_and_version
    uses: ./.github/workflows/build-and-publish-front-end.yml
    # The output is a string, hence the string comparison.
    if: ${{ needs.determine_changes_and_version.outputs.front-end-paths-changed == 'true' }}
    with:
      version-tag: ${{ needs.compute-next-version.outputs.version-tag }}
    secrets: inherit
