name: Run Elm tests

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          # Outdated. Updating to 17+ introduces a breaking change with create-elm-app.
          node-version: '16.x'
      - name: Install create-elm-app
        run: npm install create-elm-app -g
      - name: Set up Elm tests
        run:
          npm install elm-test -g
      - name: Call Elm test runner
        run: |
          cd frontend
          elm-app test