name: Run Elm tests

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Set up Node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          # Outdated. Updating to 17+ introduces a breaking change with create-elm-app.
          node-version: '16.x'
      - name: Install create-elm-app
        run: npm install create-elm-app -g
      - name: Set up Elm tests
        run:
          npm install elm-test -g
      - name: Call Elm test runner
        run: |
          cd frontend
          elm-app test