name: Run Elm tests

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Set up Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          # Outdated. Updating to 17+ introduces a breaking change with create-elm-app.
          node-version: '16.x'
      - name: Install create-elm-app
        run: npm install create-elm-app -g
      - name: Set up Elm tests
        run:
          npm install elm-test -g
      - name: Call Elm test runner
        run: |
          cd frontend
          elm-app test