name: Run Elm tests

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          # Outdated. Updating to 17+ introduces a breaking change with create-elm-app.
          node-version: '16.x'
      - name: Install create-elm-app
        run: npm install create-elm-app -g
      - name: Set up Elm tests
        run:
          npm install elm-test -g
      - name: Call Elm test runner
        run: |
          cd frontend
          elm-app test